on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: brew install fontforge woff2
      - run: curl -L http://mirrors.ctan.org/fonts/mlmodern.zip > mlmodern.zip
      - run: unzip mlmodern.zip
      - run: |
          fontforge -lang=ff -c 'Open($1); Generate($1:r + ".otf")' mlmodern/type1/mlmr12.pfb
          fontforge -lang=ff -c 'Open($1); Generate($1:r + ".otf")' mlmodern/type1/mlmri12.pfb
          fontforge -lang=ff -c 'Open($1); Generate($1:r + ".otf")' mlmodern/type1/mlmbx12.pfb
      - run: |
          mv mlmodern/type1/mlmr12.otf mlmodern/type1/mlmri12.otf mlmodern/type1/mlmbx12.otf .
      - run: |
          woff2_compress mlmr12.otf
          woff2_compress mlmri12.otf
          woff2_compress mlmbx12.otf
      - run: |
          mv mlmr12.woff2 mlmodern-regular.woff2
          mv mlmri12.woff2 mlmodern-italic.woff2
          mv mlmbx12.woff2 mlmodern-bold.woff2
      - id: short_sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.short_sha.outputs.short_sha }}
          files: |
            mlmodern-regular.woff2
            mlmodern-italic.woff2
            mlmodern-bold.woff2
