on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: brew install woff2
      - run: curl -L https://mirrors.ctan.org/fonts/newcomputermodern/otf/NewCMMath-Regular.otf > NewCMMath-Regular.otf
      - run: woff2_compress NewCMMath-Regular.otf
      - id: short_sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.short_sha.outputs.short_sha }}
          files: |
            NewCMMath-Regular.woff2
